spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <enter-your-gmail-address>
    password: <enter-your-gmail-password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true