spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: smulookid@gmail.com
    password: smulookid7016
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true